resources:
  containers:
  - container: manylinux
    image: quay.io/pypa/manylinux1_x86_64
  repositories:
  - repository: templates
    type: github
    name: Dish1306/azure-pipelines
    endpoint: aio-libs

stages:
- stage: azure_linux_deploy
  displayName: 'deploy-aarch64'
  jobs:
  - job: manylinux_aarch64
    displayName: 'Manylinux_aarch64'
    strategy:
      matrix:
        Py35 Arm64:
          python.code: 'cp35-cp35m'
          manylinux: 'manylinux_aarch64'
        Py36 Arm64:
          python.code: 'cp36-cp36m'
          manylinux: 'manylinux_aarch64'
        Py37 Arm64:
          python.code: 'cp37-cp37m'
          manylinux: 'manylinux_aarch64'
        Py38 Arm64:
          python.code: 'cp38-cp38'
          manylinux: 'manylinux_aarch64'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self
      submodules: true
      clean: true

    - script: docker run --rm --privileged hypriot/qemu-register
      displayName: 'Registering qemu'
    - script: |
        set -xeo pipefail
        docker run -v $(pwd):"${DOCKER_MULTIDICT_ROOT}":rw,z \
                   -e HOST_USER_ID \
                   "quay.io/pypa/manylinux2014_aarch64" \
                   bash -c "cd $DOCKER_MULTIDICT_ROOT;
                   /opt/python/$(python.code)/bin/python -m venv .build-venv && \
                   source .build-venv/bin/activate && \
                   pip install -U setuptools wheel && \
                   python setup.py bdist_wheel && \
                   auditwheel repair dist/*.whl --wheel-dir wheelhouse/;"
      displayName: 'Running AArch64 wheel build'
      env:
        DOCKER_MULTIDICT_ROOT: "/home/multidict_root"
        HOST_USER_ID: $(id -u)
    - template: templates/step-store-dist.yml@templates
      parameters:
        folder: wheelhouse
